### ISSUE TITLE
Can't see end of long messages because of fat emoji picker

### ISSUE THREAD

**Issue by ChillerDragon** [discord-irc/discord-irc#32]
![image](https://github.com/discord-irc/discord-irc/assets/20344300/a68e50b0-bef3-415b-bab6-68cfb7ecc2df)

how does discord solve this? Line wrap before the emoji? Scroll before the emoji?
Line wrap would be nice but also misleading because its sent as one line in the end.
Or we could split it up and sent multiple messages. But that would trigger ratelimiting faster than expected. Also its weird to get ratelimited with half of the lines being sent already.

**Comment by MilkeeyCat** [comment]
they just make it look like its one big input but its just a div with transparent input on the left and buttons on the right

**Comment by MilkeeyCat** [comment]
should we call css guy and let him do his job?

**Comment by ChillerDragon** [comment]
you mean jopsti? :D

**Comment by MilkeeyCat** [comment]
u can ask jopsi, or i can do it

**Comment by ChillerDragon** [comment]
I think jopsti is busy with dd-pg would be epic if you want to do it c:
