### ISSUE TITLE
use one rofl.svg

### ISSUE THREAD

**Issue by MilkeeyCat** [discord-irc/discord-irc#41]
now you use 2 images for the emoji button. rofl.svg and rofl_grey.svg. css has functions to greyscale image. what do you think about using just `rofl.svg` and just greyscale it?

**Comment by ChillerDragon** [comment]
Yes sounds good. I was just too lazy to do it lol

**Comment by MilkeeyCat** [comment]
if to use just greyscale() it will be a bit brighter. is it good or lower the opacity so it looks exactly like before?

**Comment by ChillerDragon** [comment]
I like how it looked before

**Comment by MilkeeyCat** [comment]
check if it looks good enough

**Comment by ChillerDragon** [comment]
LGTM
